name: Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - uses: actions/checkout@v2
        with:
           repository: EuleMitKeule/odin-inspector-3.0.7
           token: ${{ secrets.PAT }}
           path: odin/
      
      - run: |
          cp -r odin/* src/
          rm -r odin
          
      - run: |
          cd src/Assets/Plugins/Sirenix
          ls -la
      
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('src/Assets/**', 'src/Packages/**', 'src/ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: src/
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts