name: Test PR

on:
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout die-gulde
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Checkout odin-inspector
        uses: actions/checkout@v2
        with:
           repository: EuleMitKeule/odin-inspector-3.0.7
           token: ${{ secrets.PAT }}
           path: odin/
      
      - name: Move odin-inspector
        run: |
          cp -r odin/* src/
          rm -r odin
      
      - name: Cache library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('src/Assets/**', 'src/Packages/**', 'src/ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Run tests
        id: run-tests
        uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: src/
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          customParameters: -debugCodeOptimization -enableCodeCoverage -coverageOptions generateBadgeReport;assemblyFilters:+GuldeLib,+GuldeClient;pathFilters:-./src/Assets/_Project/GuldeLib/Builders/LoadAssetAttribute.cs,-./src/Assets/_Project/GuldeClient/Input/Controls.cs -coverageResultsPath coverage

      - name: Store results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: artifacts

      - name: Store coverage
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Code coverage
          path: ./src/coverage
